CapaPresentacionAdmin/Controllers/MantenimientoController.cs
using CapaEntidad;
using CapaNegocio;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Globalization;
using System.Configuration;
using System.IO;

namespace CapaPresentacionAdmin.Controllers
{
    [Authorize]
    public class MantenimientoController : Controller
    {
        // GET: Mantenimiento
        public ActionResult Categoria()
        {
            return View();
        }

        public ActionResult Marca()
        {
            return View();
        }

        public ActionResult Producto()
        {
            return View();
        }

        /*-------------CATEGORIA---------------*/
        #region Categoria
        [HttpGet]
        public JsonResult ListarCategoria()
        {
            List<Categoria> olista = new List<Categoria>();
            olista = new CN_Categoria().Listar();

            return Json(new { data = olista }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult GuardarCategoria(Categoria oCategoria)
        {
            object resultado;
            string mensaje = string.Empty;

            if (oCategoria.IdCategoria == 0)
                resultado = new CN_Categoria().Registrar(oCategoria, out mensaje);
            else
                resultado = new CN_Categoria().Editar(oCategoria, out mensaje);

            return Json(new { resultado = resultado, mensaje = mensaje }, JsonRequestBehavior.AllowGet);

        }

        [HttpPost]
        public JsonResult EliminarCategoria(int id)
        {
            bool respuesta = false;
            string mensaje = string.Empty;

            respuesta = new CN_Categoria().Eliminar(id, out mensaje);
            return Json(new { resultado = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);

        }
        #endregion
        /*-------------MARCA---------------*/
        #region Marca
        [HttpGet]
        public JsonResult ListarMarca()
        {
            List<Marca> olista = new List<Marca>();
            olista = new CN_Marca().Listar();

            return Json(new { data = olista }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult GuardarMarca(Marca oMarca)
        {
            object resultado;
            string mensaje = string.Empty;

            if (oMarca.IdMarca == 0)
                resultado = new CN_Marca().Registrar(oMarca, out mensaje);
            else
                resultado = new CN_Marca().Editar(oMarca, out mensaje);

            return Json(new { resultado = resultado, mensaje = mensaje }, JsonRequestBehavior.AllowGet);

        }

        [HttpPost]
        public JsonResult EliminarMarca(int id)
        {
            bool respuesta = false;
            string mensaje = string.Empty;

            respuesta = new CN_Marca().Eliminar(id, out mensaje);
            return Json(new { resultado = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);

        }
        #endregion
        /*-------------PRODUCTOS---------------*/
        #region Producto
        [HttpGet]
        public JsonResult ListarProducto()
        {
            List<Producto> olista = new List<Producto>();
            olista = new CN_Producto().Listar();

            return Json(new { data = olista }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult GuardarProducto(string objeto, HttpPostedFileBase archivoImagen)
        {
            string mensaje = string.Empty;
            bool operacion_exitosa = true;
            bool guardar_imagen_exito = true;

            Producto oProducto = new Producto();
            oProducto = JsonConvert.DeserializeObject<Producto>(objeto);

            decimal precio;

            if (decimal.TryParse(oProducto.PrecioTexto, NumberStyles.AllowDecimalPoint, new CultureInfo("es-NI"), out precio))
                oProducto.Precio = precio;

            else
                return Json(new { operacion_exitosa = false, mensaje = "El formato del precio debe ser ##.##" }, JsonRequestBehavior.AllowGet);

             if (oProducto.IdProducto == 0)
            { 
                int idProductoGenerado = new CN_Producto().Registrar(oProducto, out mensaje);

            if (idProductoGenerado != 0)
                oProducto.IdProducto = idProductoGenerado;
            else
                operacion_exitosa = false;
            }
            else { operacion_exitosa = new CN_Producto().Editar(oProducto, out mensaje); }
                
            if(operacion_exitosa)
            {
                if(archivoImagen != null)
                {
                    string rutaGuardar = ConfigurationManager.AppSettings["ServidorFotos"];
                    string extencionImagen = Path.GetExtension(archivoImagen.FileName);
                    string nombreImagen = string.Concat(oProducto.IdProducto.ToString(), extencionImagen);

                    try
                    {
                        archivoImagen.SaveAs(Path.Combine(rutaGuardar,nombreImagen));
                    }
                    catch(Exception ex)
                    {
                      string msg = ex.Message;
                        guardar_imagen_exito = false;
                    }

                    if (guardar_imagen_exito)
                    {
                        oProducto.RutaImagen = rutaGuardar;
                        oProducto.NombreImagen = nombreImagen;
                        bool rspta = new CN_Producto().GuardarDatosImagen(oProducto, out mensaje);
                    }
                    else
                        mensaje = "se guardo el producto pero hubo un problema con la imagen";
                }
 
            }
            return Json(new { operacion_exitosa = operacion_exitosa, idGenerado=oProducto.IdProducto, mensaje = mensaje }, JsonRequestBehavior.AllowGet);

        }
        [HttpPost]
        public JsonResult ImagenProducto(int id)
        {
            bool conversion;
            Producto oProducto = new CN_Producto().Listar().Where(p => p.IdProducto == id).FirstOrDefault();
            string textoBase64 = CN_Recursos.ConvertirBase64(Path.Combine( oProducto.RutaImagen, oProducto.NombreImagen), out conversion);

            return Json(new
            {
                conversion = conversion,
                textobase64 = textoBase64,
                extencion = Path.GetExtension(oProducto.NombreImagen)

            },
            JsonRequestBehavior.AllowGet
            ); 
        }

        [HttpPost]
        public JsonResult EliminarProducto(int id)
        {
            bool respuesta = false;
            string mensaje = string.Empty;

            respuesta = new CN_Producto().Eliminar(id, out mensaje);
            return Json(new { resultado = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }
        #endregion
    }
}

CapaPresentacionAdmin/Views/Mantenimiento/Categoria.cshtml
@{
    ViewBag.Title = "Categoria";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<ol class="breadcrumb mb-4 mt-4">
    <li class="breadcrumb-item"><a href="@Url.Action("Index","Home")">Mantenimiento</a></li>
    <li class="breadcrumb-item active">Categorias</li>
</ol>

<div class="card">
    <div class="card-header">
        <i class="fas fa-table"></i> Lista de Categorias
    </div>

    <div class="card-body">
        <div class="row">
            <div class="col-12">
                <button type="button" class="btn btn-success" onclick="AbrirModal(null)">Crear Nuevo</button>
            </div>
        </div>
        <hr />

        <table id="tablaCategoria" class="display cell-border" style="width:100%">
            <thead>
                <tr>
                    <th>Descripcion</th>
                    <th>Activo</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>

    </div>
</div>


<!-- Modal --> <!-- data-bs-backdrop="static"= modal solo cierra al precionar cerrar o x -->
<div class="modal fade" id="formModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true" data-bs-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header bg-dark text-white">
                <h5 class="modal-title" id="exampleModalLabel">Categoria</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body ">
                <div class="row g-1">


                    <input type="hidden" id="txtIdCategoria" value="0">

                    <div class="col-sm-6">
                        <label for="txtDescripcion" class="form-label">Descripcion</label>
                        <input type="text" class="form-control" id="txtDescripcion" autocomplete="off">
                    </div>

                    <div class="col-sm-6">
                        <label for="cboActivo" class="form-label">Activo</label>
                        <select class="form-select" id="cboActivo">
                            <option value="1">Si</option>
                            <option value="0">No</option>
                        </select>
                    </div>

                </div>

                <div class="row mt-2">
                    <div class="col-12">
                        <div id="mensajeError" class="alert alert-danger" role="alert">
                            A simple danger alert—check it out!
                        </div>
                    </div>
                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                <button type="button" class="btn btn-primary" onclick="Guardar()">Guardar</button>
            </div>
        </div>
    </div>
</div>

@section scripts{
    <script>

        var tabladata;
        var filaSeleccionada;

        tabladata = $("#tablaCategoria").DataTable({
            responsive: true,
            ordering: false,
            "ajax": {
                url: '@Url.Action("ListarCategoria","Mantenimiento")',
                type: 'GET',
                dataType: 'json'
            },
            "columns": [
                { "data": "Descripcion" },
                {
                    "data": "Activo","render":function(valor) {
                        if (valor)
                            return '<span class="badge bg-success">Si</span>'

                        else
                            return '<span class="badge bg-danger">No</span >'

                    }

                },
                {
                    "defaultContent": '<button type="button" class="btn btn-primary btn-sm btn-editar"><i class="fas fa-pen me-1" ></i></button>' +
                        '<button type="button" class="btn btn-danger btn-sm ms-2 btn-eliminar"><i class="fas fa-trash me-1" ></i></button>',
                    "orderable" :false,
                    "searchable": false,
                    "width": "90px"
                }

            ],
            "language": {
                "url":"//cdn.datatables.net/plug-ins/1.13.3/i18n/es-MX.json"
            }

        });

        function AbrirModal(json) {

            /*para que los texbox del modal esten limpios al abrir el modal */
            $("#txtIdCategoria").val(0);
            $("#txtDescripcion").val("");
            $("#cboActivo").val(1);
            $("#mensajeError").hide();

            if (json != null)
            {
                /*para UrlAction llenar los texbox del modal con la data */
                $("#txtIdCategoria").val(json.IdCategoria);
                $("#txtDescripcion").val(json.Descripcion);
                $("#cboActivo").val(json.Activo == true ? 1 : 0);
            }

            $("#formModal").modal("show");
        }

        /*para el boton modificar */
        $("#tablaCategoria tbody").on("click", '.btn-editar', function () {

             filaSeleccionada = $(this).closest("tr");
            var data = tabladata.row(filaSeleccionada).data();

            console.log(data);
            AbrirModal(data)
        })

        //para el boton de eliminar
        $("#tablaCategoria tbody").on("click", '.btn-eliminar', function () {

            var categoriaSeleccionada = $(this).closest("tr");
            var data = tabladata.row(categoriaSeleccionada).data();

            console.log(data);

            swal({
                title: "Estas Seguro?",
                text: "Desea eliminar la Categoria ?",
                type: "warning",
                showCancelButton: true,
                confirmButtonClass: "btn-primary",
                confirmButtonText: "Si",
                cancelButtonText:"No",
                closeOnConfirm: true
            },
                function () {

                    jQuery.ajax({

                url: '@Url.Action("EliminarCategoria", "Mantenimiento")',
                type: 'POST',
                data: JSON.stringify({ id: data.IdCategoria }),
                dataType: 'json',
                contentType: 'application/json; charset=utf-8',
                success: function (data) {

                    if (data.resultado)
                        tabladata.row(categoriaSeleccionada).remove().draw();
                    else
                        swal("No se pudo eliminar", data.mensaje, "error");
                },
                error: function (error) {
                    console.log(error);
                }

            });
                });
        })

        /*Funcion guardar */
        function Guardar()
        {
            var Categoria = {

                IdCategoria: $("#txtIdCategoria").val(),
                Descripcion: $("#txtDescripcion").val(),
                Activo: $("#cboActivo").val() == 1 ? true : false
            }

            jQuery.ajax({
                //guardar Categoria es el nombre del metodo y  Mantenimiento el nombre del controlador
                url: '@Url.Action("GuardarCategoria", "Mantenimiento")',
                type: 'POST',
                data: JSON.stringify({ oCategoria: Categoria }),
                dataType: 'json',
                contentType: 'application/json; charset=utf-8',
                success: function (data) {

                    //categoria nueva
                    if (Categoria.IdCategoria == 0) {

                        if (data.resultado != 0) {
                            Categoria.IdCategoria = data.resultado;
                            tabladata.row.add(Categoria).draw(false);
                            $("#formModal").modal("hide");
                        }
                        else {
                            $("#mensajeError").text(data.mensaje);
                            $("#mensajeError").show();

                        }

                    }

                    //Categoria existente
                    else {
                        if (data.resultado)
                        {
                            tabladata.row(filaSeleccionada).data(Categoria).draw(false);
                            filaSeleccionada = null;
                            $("#formModal").modal("hide");

                        }
                        else {
                            $("#mensajeError").text(data.mensaje);
                            $("#mensajeError").show();
                        }
                    }

                },
                error: function (error) {
                    console.log(error);
                },
                beforeSend: function () {

                }
            });
        }



    </script>


}

CapaPresentacionAdmin/Views/Mantenimiento/Marca.cshtml
@{
    ViewBag.Title = "Marca";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<ol class="breadcrumb mb-4 mt-4">
    <li class="breadcrumb-item"><a href="@Url.Action("Index","Home")">Mantenimiento</a></li>
    <li class="breadcrumb-item active">Marcas</li>
</ol>

<div class="card">
    <div class="card-header">
        <i class="fas fa-bookmark"></i> Lista de Marcas
    </div>

    <div class="card-body">
        <div class="row">
            <div class="col-12">
                <button type="button" class="btn btn-success" onclick="AbrirModal(null)">Crear Nuevo</button>
            </div>
        </div>
        <hr />

        <table id="tablaMarca" class="display cell-border" style="width:100%">
            <thead>
                <tr>
                    <th>Descripcion</th>
                    <th>Activo</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>

    </div>
</div>


<!-- Modal --> <!-- data-bs-backdrop="static"= modal solo cierra al precionar cerrar o x -->
<div class="modal fade" id="formModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true" data-bs-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header bg-dark text-white">
                <h5 class="modal-title" id="exampleModalLabel">Marca</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body ">
                <div class="row g-1">


                    <input type="hidden" id="txtIdMarca" value="0">

                    <div class="col-sm-6">
                        <label for="txtDescripcion" class="form-label">Descripcion</label>
                        <input type="text" class="form-control" id="txtDescripcion" autocomplete="off">
                    </div>

                    <div class="col-sm-6">
                        <label for="cboActivo" class="form-label">Activo</label>
                        <select class="form-select" id="cboActivo">
                            <option value="1">Si</option>
                            <option value="0">No</option>
                        </select>
                    </div>

                </div>

                <div class="row mt-2">
                    <div class="col-12">
                        <div id="mensajeError" class="alert alert-danger" role="alert">
                            A simple danger alert—check it out!
                        </div>
                    </div>
                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                <button type="button" class="btn btn-primary" onclick="Guardar()">Guardar</button>
            </div>
        </div>
    </div>
</div>

@section scripts{
    <script>

        var tabladata;
        var filaSeleccionada;

        tabladata = $("#tablaMarca").DataTable({
            responsive: true,
            ordering: false,
            "ajax": {
                url: '@Url.Action("ListarMarca","Mantenimiento")',
                type: 'GET',
                dataType: 'json'
            },
            "columns": [
                { "data": "Descripcion" },
                {
                    "data": "Activo","render":function(valor) {
                        if (valor)
                            return '<span class="badge bg-success">Si</span>'

                        else
                            return '<span class="badge bg-danger">No</span >'

                    }

                },
                {
                    "defaultContent": '<button type="button" class="btn btn-primary btn-sm btn-editar"><i class="fas fa-pen me-1" ></i></button>' +
                        '<button type="button" class="btn btn-danger btn-sm ms-2 btn-eliminar"><i class="fas fa-trash me-1" ></i></button>',
                    "orderable" :false,
                    "searchable": false,
                    "width": "90px"
                }

            ],
            "language": {
                "url":"//cdn.datatables.net/plug-ins/1.13.3/i18n/es-MX.json"
            }

        });

        function AbrirModal(json) {

            /*para que los texbox del modal esten limpios al abrir el modal */
            $("#txtIdMarca").val(0);
            $("#txtDescripcion").val("");
            $("#cboActivo").val(1);
            $("#mensajeError").hide();

            if (json != null)
            {
                /*para UrlAction llenar los texbox del modal con la data */
                $("#txtIdMarca").val(json.IdMarca);
                $("#txtDescripcion").val(json.Descripcion);
                $("#cboActivo").val(json.Activo == true ? 1 : 0);
            }

            $("#formModal").modal("show");
        }

        /*para el boton modificar */
        $("#tablaMarca tbody").on("click", '.btn-editar', function () {

             filaSeleccionada = $(this).closest("tr");
            var data = tabladata.row(filaSeleccionada).data();

            console.log(data);
            AbrirModal(data)
        })

        //para el boton de eliminar
        $("#tablaMarca tbody").on("click", '.btn-eliminar', function () {

            var MarcaSeleccionada = $(this).closest("tr");
            var data = tabladata.row(MarcaSeleccionada).data();

            console.log(data);

            swal({
                title: "Estas Seguro?",
                text: "Desea eliminar la Marca ?",
                type: "warning",
                showCancelButton: true,
                confirmButtonClass: "btn-primary",
                confirmButtonText: "Si",
                cancelButtonText:"No",
                closeOnConfirm: true
            },
                function () {

                    jQuery.ajax({

                url: '@Url.Action("EliminarMarca", "Mantenimiento")',
                type: 'POST',
                data: JSON.stringify({ id: data.IdMarca }),
                dataType: 'json',
                contentType: 'application/json; charset=utf-8',
                success: function (data) {

                    if (data.resultado)
                        tabladata.row(MarcaSeleccionada).remove().draw();
                    else
                        swal("No se pudo eliminar", data.mensaje, "error");
                },
                error: function (error) {
                    console.log(error);
                }

            });
                });
        })

        /*Funcion guardar */
        function Guardar()
        {
            var Marca = {

                IdMarca: $("#txtIdMarca").val(),
                Descripcion: $("#txtDescripcion").val(),
                Activo: $("#cboActivo").val() == 1 ? true : false
            }

            jQuery.ajax({
                //guardar Marca es el nombre del metodo y  Mantenimiento el nombre del controlador
                url: '@Url.Action("GuardarMarca", "Mantenimiento")',
                type: 'POST',
                data: JSON.stringify({ oMarca: Marca }),
                dataType: 'json',
                contentType: 'application/json; charset=utf-8',
                success: function (data) {

                    //Marca nueva
                    if (Marca.IdMarca == 0) {

                        if (data.resultado != 0) {
                            Marca.IdMarca = data.resultado;
                            tabladata.row.add(Marca).draw(false);
                            $("#formModal").modal("hide");
                        }
                        else {
                            $("#mensajeError").text(data.mensaje);
                            $("#mensajeError").show();

                        }

                    }

                    //Marca existente
                    else {
                        if (data.resultado)
                        {
                            tabladata.row(filaSeleccionada).data(Marca).draw(false);
                            filaSeleccionada = null;
                            $("#formModal").modal("hide");

                        }
                        else {
                            $("#mensajeError").text(data.mensaje);
                            $("#mensajeError").show();
                        }
                    }

                },
                error: function (error) {
                    console.log(error);
                },
                beforeSend: function () {

                }
            });
        }



    </script>


}